export const CHECK_URL = '/check-my-rental-readiness';

export const INTENT_KEYS = [
  'bad_credit',
  'eviction',
  'broken_lease',
  'denied_application',
  'income_requirements',
  'no_credit',
  'approval_requirements',
  'second_chance',
  'general_renter',
];

export const INTENT_PAGES = {
  bad_credit: {
    route: '/apartments-with-bad-credit',
    title: 'Renting With Bad Credit? Check Your Rental Readiness | RentReady',
    description: 'Worried bad credit could affect your apartment search? Check your rental readiness, see what may need attention, and prepare before you apply.',
    eyebrow: 'RENTING WITH BAD CREDIT',
    h1: 'Bad Credit? Know Where You Stand Before You Apply.',
    subhead: 'Your credit score is important, but it may not be the only thing a property looks at.',
    body: 'RentReady helps you look at your income, credit range, rental history, and other information you provide so you can better understand what to prepare before applying.',
    primaryCta: 'CHECK WHERE I STAND',
    sectionH2: "Bad Credit Doesn't Tell the Whole Story.",
    sectionBody: ['Rental requirements vary by property. Some may look at several parts of your application, including income, credit, rental history, and other screening information.', 'RentReady helps you organize the information you already know about yourself before you spend money applying.'],
    secondH2: 'See What May Need Attention.',
    bullets: ['Your income-to-rent fit', 'Your credit range', 'Your rental history', 'Your move timing', 'Possible co-signer considerations', 'Questions to ask before applying'],
    finalHeadline: 'Check Your Rental Readiness Before You Apply.',
    finalCta: 'CHECK MY RENTAL READINESS',
    faq: [
      ['Can I rent an apartment with bad credit?', 'It may be possible. Rental requirements vary by property, and credit may be only one part of the screening process.'],
      ['Does RentReady approve me for an apartment?', 'No. RentReady helps you understand your rental situation based on the information you provide. Each property makes its own approval decision.'],
      ['Does RentReady pull my credit?', 'No. RentReady uses the information you provide.'],
    ],
    related: ['approval_requirements', 'income_requirements', 'no_credit'],
  },
  eviction: {
    route: '/rent-after-eviction',
    title: 'Renting After an Eviction? See What to Check First | RentReady',
    description: 'Trying to rent after an eviction? Understand what may need attention before your next apartment application.',
    eyebrow: 'RENTING AFTER AN EVICTION',
    h1: 'Have a Past Eviction? Start With What You Can Control.',
    subhead: 'Before your next application, understand your rental situation and what you may want to ask the property first.',
    primaryCta: 'SEE WHERE I STAND',
    sectionH2: "Don't Go Into Your Next Application Blind.",
    sectionBody: ['A past eviction may matter during rental screening, but requirements are not the same everywhere.', 'RentReady helps you review the information you provide so you can prepare questions, documents, and your next step before applying.'],
    secondH2: 'Know What to Prepare.',
    bullets: ['Your current income and rent budget', 'Your credit range', 'Your rental-history situation', 'Your move timing', 'Questions to ask the leasing office', 'What may need attention before applying'],
    finalHeadline: 'Before You Apply Again, Check Where You Stand.',
    finalCta: 'CHECK MY RENTAL SITUATION',
    faq: [
      ['Can I rent again after an eviction?', 'Requirements vary by property. A past eviction may affect screening, but it does not tell you what every property will decide.'],
      ['Does RentReady find apartments that guarantee eviction approval?', 'No. RentReady does not guarantee property approval. We help you understand your situation and continue your apartment search more prepared.'],
      ['Should I ask about screening before I pay an application fee?', "Yes. It can be helpful to ask a property about its screening requirements before applying."],
    ],
    related: ['broken_lease', 'second_chance', 'denied_application'],
  },
  broken_lease: {
    route: '/rent-after-broken-lease',
    title: 'Renting After a Broken Lease? Check Your Next Step | RentReady',
    description: 'Have a past broken lease? Check your rental readiness and see what to prepare before your next apartment application.',
    eyebrow: 'RENTING AFTER A BROKEN LEASE',
    h1: 'Broken Lease in Your Past? Prepare Before Your Next Application.',
    subhead: 'See where your rental profile stands and what may be worth checking before you apply again.',
    primaryCta: 'SEE MY NEXT STEP',
    sectionH2: 'Your Past Lease Is One Part of the Picture.',
    sectionBody: ['Properties can use different rental-screening rules. A past lease issue may matter, but other parts of your current situation may matter too.', 'RentReady helps you organize the information you provide before your next application.'],
    secondH2: 'Go In With a Plan.',
    bullets: ['Review your current rental budget', 'Understand your credit range', 'Prepare your rental-history details', 'Know what questions to ask', 'See what may need attention', 'Continue your apartment search'],
    finalHeadline: 'Check Before You Apply Again.',
    finalCta: 'CHECK WHERE I STAND',
    faq: [
      ['Can a broken lease affect renting another apartment?', 'It can affect rental screening depending on the property and the information reported.'],
      ['Does RentReady remove a broken lease?', 'No. RentReady provides rental-readiness guidance and helps you understand what to prepare for your apartment search.'],
      ['Will RentReady guarantee another apartment?', 'No. Final rental decisions are made by each property.'],
    ],
    related: ['eviction', 'second_chance', 'denied_application'],
  },
  denied_application: {
    route: '/apartment-application-denied',
    title: 'Apartment Application Denied? Know What to Do Next | RentReady',
    description: 'Recently denied for an apartment? Before you apply again, check your rental situation and see what may need attention.',
    eyebrow: 'RECENTLY DENIED?',
    h1: 'Before You Apply Again, Find Out What May Need Attention.',
    subhead: 'Another application may cost more money. Take a few minutes to look at your rental situation first.',
    primaryCta: 'CHECK BEFORE I APPLY AGAIN',
    sectionH2: "A Denial Doesn't Tell You Your Next Move.",
    sectionBody: ['Rental applications can be affected by different screening factors.', 'Before you apply somewhere else, it helps to understand your income, credit range, rental history, and any information the property gave you about its decision.'],
    secondH2: 'Turn the Denial Into a Plan.',
    bullets: ['Review the reason you were given', 'Check your current income-to-rent fit', 'Review your credit range', 'Think through your rental history', 'Prepare questions for the next property', 'See what may need attention first'],
    finalHeadline: "Don't Pay Another Application Fee Without a Plan.",
    finalCta: 'CHECK MY RENTAL SITUATION',
    faq: [
      ['Why was my apartment application denied?', 'The reason can vary. Properties may use income, credit, rental history, tenant-screening information, or other requirements.'],
      ['Should I apply somewhere else right away?', "You can, but it may help to understand the reason for the first decision and ask about the next property's requirements before paying another application fee."],
      ['Can RentReady reverse a denial?', 'No. RentReady helps you understand your rental situation and prepare for your next step.'],
    ],
    related: ['approval_requirements', 'bad_credit', 'income_requirements'],
  },
  income_requirements: {
    route: '/apartment-income-requirements',
    title: 'Do You Make Enough to Rent the Apartment? | RentReady',
    description: 'Not sure if your income fits the rent you want? Check your income-to-rent fit and rental readiness before applying.',
    eyebrow: 'INCOME & RENT',
    h1: 'Do You Make Enough for the Rent You Want?',
    subhead: 'See how your income compares with your monthly rent target before you apply.',
    primaryCta: 'CHECK MY RENT FIT',
    sectionH2: 'Start With the Numbers.',
    sectionBody: ['Many properties use income requirements, but the exact rule can vary.', 'RentReady compares the income and rent information you provide so you can better understand your current fit.'],
    secondH2: 'See Your Income-to-Rent Picture.',
    bullets: ['Your reported household income', 'Your target monthly rent', 'Your estimated income-to-rent fit', 'Other rental-readiness factors', 'Questions to confirm with the property', 'Your next step before applying'],
    finalHeadline: 'Check Your Rent Fit Before You Apply.',
    finalCta: 'CHECK MY RENT FIT',
    faq: [
      ['What is the 3x rent rule?', 'Some properties use an income guideline based on a multiple of monthly rent, but requirements vary by property.'],
      ['Does every apartment require three times the rent?', 'No. Income requirements can vary.'],
      ['Does RentReady verify my income?', 'The RentReady review is based on the information you provide unless a specific feature clearly says otherwise.'],
    ],
    related: ['approval_requirements', 'bad_credit', 'first_apartment_no_credit'],
  },
  no_credit: {
    route: '/first-apartment-no-credit',
    title: 'First Apartment With Little or No Credit? Start Here | RentReady',
    description: 'Looking for your first apartment with little or no credit history? Check your rental readiness and see what to prepare before applying.',
    eyebrow: 'FIRST APARTMENT',
    h1: 'Little or No Credit? You Can Still Prepare for Your First Apartment.',
    subhead: 'See what information may matter before you start paying application fees.',
    primaryCta: 'CHECK MY READINESS',
    sectionH2: 'No Credit Is Not the Same as Bad Credit.',
    sectionBody: ['If you have a limited credit or rental history, a property may look at other information when reviewing an application.', 'RentReady helps you think through the information you can prepare before applying.'],
    secondH2: 'Get Ready Before You Apply.',
    bullets: ['Your income and rent budget', 'Your current credit range', 'Your employment information', 'Your rental-history situation', 'Possible co-signer considerations', 'Questions to ask the property'],
    finalHeadline: 'Start Your First Apartment Search More Prepared.',
    finalCta: 'CHECK MY RENTAL READINESS',
    faq: [
      ['Can I rent my first apartment with no credit?', 'Requirements vary by property. Limited credit history does not automatically tell you what a property will decide.'],
      ['Will I need a co-signer?', "Some properties may require one depending on their rules and the application. RentReady cannot determine a property's final requirement."],
      ['Does RentReady build my credit?', 'No. The RentReady Review helps you understand your rental-readiness situation.'],
    ],
    related: ['bad_credit', 'income_requirements', 'approval_requirements'],
  },
  approval_requirements: {
    route: '/apartment-approval-requirements',
    title: 'Will You Get Approved for an Apartment? Check First | RentReady',
    description: "Wondering if you'll get approved for an apartment? Check your rental readiness and see what may need attention before you apply.",
    eyebrow: 'APARTMENT APPROVAL',
    h1: "Wondering If You'll Get Approved?",
    subhead: 'Before you spend money applying, see how the rental information you provide fits together.',
    primaryCta: 'CHECK WHERE I STAND',
    sectionH2: 'Approval Is More Than One Number.',
    sectionBody: ['Properties can look at several parts of a rental application.', 'RentReady helps you review your income, rent budget, credit range, rental history, and other information you provide.'],
    secondH2: "Know What You're Walking In With.",
    bullets: ['Income-to-rent fit', 'Credit range', 'Rental history', 'Move timing', 'Possible co-signer considerations', 'Questions to ask before applying'],
    finalHeadline: 'Know More Before You Apply.',
    finalCta: 'CHECK MY RENTAL READINESS',
    faq: [
      ['What do apartments check before approving you?', 'Screening can vary, but properties may consider income, credit, rental history, identity information, and other requirements.'],
      ['Can RentReady tell me if a property will approve me?', 'No. RentReady provides an educational rental-readiness outlook. The property makes the final decision.'],
      ['Does checking my RentReady outlook hurt my credit?', 'No. RentReady does not pull your credit for this review.'],
    ],
    related: ['bad_credit', 'income_requirements', 'denied_application'],
  },
  second_chance: {
    route: '/second-chance-apartments',
    title: 'Looking for Second Chance Apartments? Start With Your Rental Situation | RentReady',
    description: 'Searching for second chance apartments? Check your rental situation first and prepare for your next apartment application.',
    eyebrow: 'SECOND CHANCE APARTMENT SEARCH',
    h1: 'Looking for Another Chance to Rent?',
    subhead: 'Start by understanding your rental situation before you spend money applying.',
    primaryCta: 'CHECK MY RENTAL SITUATION',
    sectionH2: 'Start With What You Know.',
    sectionBody: ['People search for second chance apartments for many reasons, including credit problems, rental history, past evictions, or previous denials.', 'RentReady helps you organize the information you provide and prepare for your next apartment search.'],
    secondH2: 'Search With Better Questions.',
    bullets: ['Understand your current rental profile', 'Know what may need attention', 'Prepare your rental-history information', 'Check your income-to-rent fit', 'Know what to ask before applying', 'Continue to apartment options'],
    finalHeadline: 'See Where You Stand Before Your Next Application.',
    finalCta: 'CHECK MY RENTAL READINESS',
    faq: [
      ['What are second chance apartments?', 'The phrase is commonly used by renters looking for properties that may consider applicants with rental or credit challenges. Individual property requirements vary.'],
      ['Does RentReady guarantee second chance approval?', 'No. RentReady does not guarantee approval or claim that every listed property accepts a specific rental history.'],
      ['Can RentReady help me prepare before applying?', 'Yes. The RentReady Review helps you understand the information you provide and what may be worth checking before your next application.'],
    ],
    related: ['eviction', 'broken_lease', 'denied_application'],
  },
};

export const INTENT_LABELS = {
  bad_credit: 'Bad Credit',
  eviction: 'Past Eviction',
  broken_lease: 'Broken Lease',
  denied_application: 'Recently Denied',
  income_requirements: 'Income Requirements',
  no_credit: 'First Apartment or No Credit',
  approval_requirements: 'Apartment Approval Requirements',
  second_chance: 'Second Chance Apartment Search',
};
