// AUTO-GENERATED by scripts/migrate-pages-to-react.mjs from rentready-review-checkout.html.
// The imported .html/.css/.js files are verbatim extracts of the original
// page. Do not hand-edit the extracted files without re-running the
// migration script, or the two will drift.
import bodyHtml from './page.html?raw';
import styles from './page.css?raw';
import headExtras from './head-extras.html?raw';
import script0 from './script-0.js?raw';
import { useLegacyPage } from '../../legacy/useLegacyPage';

export default function RentreadyReviewCheckout() {
  const containerRef = useLegacyPage({
    title: "RentReady Network - Secure Checkout",
    headExtras,
    styles,
    bodyHtml,
    scripts: [script0],
  });
  return <div ref={containerRef} />;
}
